export const perceptionBlocks = [
  {
    type: "get_arena_width",
    message0: "larghezza arena",
    output: "Number",
    colour: 230,
    tooltip: "Restituisce la larghezza dell'arena.",
    helpUrl: "",
  },
  {
    type: "get_arena_height",
    message0: "altezza arena",
    output: "Number",
    colour: 230,
    tooltip: "Restituisce l'altezza dell'arena.",
    helpUrl: "",
  },
  {
    type: "is_projectile_incoming",
    message0: "proiettile in arrivo?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se un proiettile sta per colpire il bot.",
    helpUrl: "",
  },
  {
    type: "is_wall_collision",
    message0: "collisione con muro?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se il bot sta per collidere con un muro.",
    helpUrl: "",
  },
  {
    type: "context_can_fire",
    message0: "il bot può sparare?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se il bot può sparare in questo tick.",
    helpUrl: "",
  },
  {
    type: "context_is_moving",
    message0: "il bot si sta muovendo?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se il bot è in movimento.",
    helpUrl: "",
  },
  {
    type: "was_hit",
    message0: "colpito da proiettile?",
    output: "Boolean",
    colour: 230,
    tooltip:
      "Restituisce vero se il bot è stato colpito da un proiettile nell'ultimo tick.",
    helpUrl: "",
  },
  {
    type: "get_enemy_position",
    message0: "posizione nemico",
    output: "Position",
    colour: 230,
    tooltip:
      "Restituisce la posizione {x, y} del nemico visibile. Se nessun nemico è visibile, restituisce null.",
    helpUrl: "",
  },
  {
    type: "is_enemy_visible",
    message0: "nemico visibile?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se un nemico è attualmente visibile.",
    helpUrl: "",
  },
  {
    type: "context_battery_percent",
    message0: "percentuale batteria",
    output: "Number",
    colour: 230,
    tooltip: "Restituisce la percentuale di batteria rimanente (da 0 a 100).",
    helpUrl: "",
  },
  {
    type: "get_enemy_distance",
    message0: "distanza nemico",
    output: "Number",
    colour: 230,
    tooltip:
      "Restituisce la distanza dal nemico visibile. Se nessun nemico è visibile, restituisce -1.",
    helpUrl: "",
  },
  {
    type: "get_enemy_angle",
    message0: "angolo nemico",
    output: "Number",
    colour: 230,
    tooltip:
      "Restituisce l'angolo relativo del nemico visibile (da -180 a 180 gradi). Se nessun nemico è visibile, restituisce 0.",
    helpUrl: "",
  },
  {
    type: "is_turret_aligned",
    message0: "torretta allineata?",
    output: "Boolean",
    colour: 230,
    tooltip:
      "Restituisce vero se la torretta è puntata verso il nemico visibile (con una piccola tolleranza).",
    helpUrl: "",
  },
  {
    type: "context_my_x",
    message0: "mia posizione X",
    output: "Number",
    colour: 230,
    tooltip: "Restituisce la coordinata X attuale del bot.",
    helpUrl: "",
  },
  {
    type: "context_my_y",
    message0: "mia posizione Y",
    output: "Number",
    colour: 230,
    tooltip: "Restituisce la coordinata Y attuale del bot.",
    helpUrl: "",
  },
  {
    type: "api_is_queue_empty",
    message0: "coda azioni vuota?",
    output: "Boolean",
    colour: 230,
    tooltip: "Restituisce vero se non ci sono azioni in coda per il bot.",
    helpUrl: "",
  },
  {
    type: "api_is_obstacle_ahead",
    message0: "ostacolo di fronte?",
    output: "Boolean",
    colour: 230,
    tooltip:
      "Restituisce vero se c'è un ostacolo direttamente di fronte al bot.",
    helpUrl: "",
  },
  {
    type: "api_is_position_valid",
    message0: "posizione %1 valida?",
    args0: [
      {
        type: "input_value",
        name: "POSITION",
        check: "Position",
      },
    ],
    output: "Boolean",
    colour: 230,
    tooltip:
      "Restituisce vero se la posizione specificata è all'interno dell'arena e non è dentro un ostacolo.",
    helpUrl: "",
  },
  {
    type: "api_get_state",
    message0: "nome stato attuale",
    output: "String",
    colour: 230,
    tooltip: "Restituisce il nome dello stato attuale della macchina a stati.",
    helpUrl: "",
  },
  {
    type: "api_get_random_point",
    message0: "punto casuale",
    output: "Position",
    colour: 230,
    tooltip: "Restituisce una posizione {x, y} casuale all'interno dell'arena.",
    helpUrl: "",
  },
  {
    type: "api_is_line_of_sight_clear",
    message0: "linea di vista libera a %1 ?",
    args0: [
      {
        type: "input_value",
        name: "POSITION",
        check: "Position",
      },
    ],
    output: "Boolean",
    colour: 230,
    tooltip:
      "Restituisce vero se non ci sono ostacoli tra il bot e la posizione specificata.",
    helpUrl: "",
  },
  {
    type: "api_scan_obstacles",
    message0: "scansiona ostacoli",
    output: "Array",
    colour: 230,
    tooltip:
      "Restituisce una lista di ostacoli vicini. Ogni ostacolo è un oggetto con x, y, width, height.",
    helpUrl: "",
  },
  {
    type: "api_get_events",
    message0: "ottieni eventi recenti",
    output: "Array",
    colour: 230,
    tooltip:
      "Restituisce una lista di eventi accaduti nell'ultimo tick (es. collisioni, colpi ricevuti).",
  },
];
